name: Maven Verify

# Controls when the action will run. 
on:
  push:
    branches:
      - '*'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # see https://github.com/actions/setup-java
      - name: Set up JDK 11 and .m2/settings.xml
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - id: verify
        name: maven verify
        run: mvn --no-transfer-progress --batch-mode verify